### ISSUE TITLE
App reference to Params 

### ISSUE THREAD

**Issue by leonardfernando** [toropeza/AppInventorJavaBridge#2]
Bug in reference to params for PaintPot, No Texting While Driving, and Pong apps.

**Comment by toropeza** [comment]
@leonardfernando Check to see if this fixed the issue for PaintPot, No Texting While Driving, and Pong.

**Comment by leonardfernando** [comment]
Im trying to generate the java project, but as soon I click the apps in my
projects, there is a server error for your version.

**Comment by toropeza** [comment]
@leonardfernando 
Hey leonard the instance is working now, but start using[ this one](https://dev-dot-javabridge-thomas.appspot.com/) for testing. The other one is used for demo purposes so it needs to remain stable.

**Comment by leonardfernando** [comment]
Okay, thank you!
