### ISSUE TITLE
Text.Join

### ISSUE THREAD

**Issue by AnaeliaOvalle** [toropeza/AppInventorJavaBridge#27]
Using the join component under text to concatenate a birthday under "DD/MM/YY" results as "DDYY//MM".

Example from test app:

<img width="426" alt="screen shot 2016-07-07 at 6 47 14 pm" src="https://cloud.githubusercontent.com/assets/12179019/16675157/4218ee3a-4473-11e6-9993-c05093b29420.png">

Generated as: 

  public void DatePicker1AfterDateSet(){
    **birthHere.Text((DatePicker1.Day()).toString() + (DatePicker1.Year()).toString() + ("/").toString() + ("/").toString() + (DatePicker1.Month()).toString());**
    if((String.valueOf(birthHere.Text()).compareTo(String.valueOf("1/10/1995")) == 0)){
      Notify.Text("Yes we do!!");
      Sound1.Vibrate(500);
    }

**Comment by toropeza** [comment]
This is generating fine for me when I created a simple app that joins text from the date picker in a similar way.
