### ISSUE TITLE
Non- Static Method

### ISSUE THREAD

**Issue by AnaeliaOvalle** [toropeza/AppInventorJavaBridge#31]
<img width="485" alt="wackyminigolf nonstaticmethod" src="https://cloud.githubusercontent.com/assets/12179019/17001787/548aa126-4e7d-11e6-80c4-2ee4cf8d2d24.png">

Issue with static versus non-static methods. Game: WackyMiniGolf

**Comment by toropeza** [comment]
(Working now)
