### ISSUE TITLE
Text registering string vs int

### ISSUE THREAD

**Issue by AnaeliaOvalle** [toropeza/AppInventorJavaBridge#33]
<img width="234" alt="wackyminigolf intinstringmethod" src="https://cloud.githubusercontent.com/assets/12179019/17001874/aea0c398-4e7d-11e6-879e-e5e37642b682.png">

Trouble entering numbers within text components. Game: WackyMiniGolf

**Comment by toropeza** [comment]
This issue was caused by the SelectRandomItem block not being supported in the Code Generator. 

(Now working)
