### ISSUE TITLE
Extra semi colons for .Colliding With methods

### ISSUE THREAD

**Issue by AnaeliaOvalle** [toropeza/AppInventorJavaBridge#35]
<img width="377" alt="1 brickbreakfinal ifcondition" src="https://cloud.githubusercontent.com/assets/12179019/17002109/b79bba06-4e7e-11e6-844c-5c3ddc66cb14.png">

Any methods regarding .collidingWith will have an extra semi colon. Game: BrickBreakFinal

**Comment by toropeza** [comment]
(Working)
