### ISSUE TITLE
Double-quoted string conflict

### ISSUE THREAD

**Issue by AnaeliaOvalle** [toropeza/AppInventorJavaBridge#36]
<img width="794" alt="wackyminigolf stringquotes" src="https://cloud.githubusercontent.com/assets/12179019/17002168/e8ea8d3a-4e7e-11e6-8ac8-e55d7230ef23.png">

Double-quoted string problem for text. Recommend having text in any string to convert into single quotes. Game: wackyMiniGolf

**Comment by toropeza** [comment]
(Working)
